// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmgodpzwxjyrecfsymcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZ29kcHp3eGp5cmVjZnN5bWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjQ1NzMsImV4cCI6MjA2ODc0MDU3M30.Uu4_9LEo8psYPaTuj4z0Y1-QI-F3fvqii_GqyzEKArs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});